# Generated by Django 4.1.2 on 2024-02-15 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CitiesModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("state_id", models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CountriesDialCodeModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("country_dial_code", models.CharField(max_length=10)),
                ("country_code", models.CharField(max_length=5)),
                ("country_name", models.CharField(max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CountriesModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("country_code", models.CharField(max_length=5)),
                ("country_name", models.CharField(max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatesModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("state_code", models.CharField(max_length=5)),
                ("country_id", models.IntegerField(blank=True, default=0)),
                ("state_name", models.CharField(max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
