# Generated by Django 4.1.2 on 2024-02-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionforfemalemodel",
            name="is_deleted",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="questionformalemodel",
            name="is_deleted",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
