# Generated by Django 4.1.2 on 2024-02-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answerOfQuestions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answersoffemalesmodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="answersofmalesmodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
