# Generated by Django 4.1.2 on 2024-02-15 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(default="", max_length=100)),
                ("last_name", models.CharField(default="", max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("gender", models.CharField(default="", max_length=10)),
                ("birth_date", models.DateField(default=None)),
                ("images", models.JSONField(default=list)),
                ("height", models.CharField(default="", max_length=10)),
                ("weight", models.CharField(default="", max_length=10)),
                (
                    "instagram_id",
                    models.CharField(default="", max_length=100, null=True),
                ),
                (
                    "instagram_account_link",
                    models.CharField(default="", max_length=255, null=True),
                ),
                ("is_free_trial_user", models.BooleanField(default=True, null=True)),
                ("is_verified", models.BooleanField(default=False, null=True)),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("designation", models.CharField(default="", max_length=100)),
                ("occupation", models.CharField(default="", max_length=100)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.citiesmodel",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.countriesmodel",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.statesmodel",
                    ),
                ),
            ],
        ),
    ]
