# Generated by Django 4.1.2 on 2024-02-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
            ],
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="images",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="images",
            field=models.ManyToManyField(to="user.file"),
        ),
    ]
