# Generated by Django 4.1.2 on 2024-02-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_file_remove_usermodel_images_usermodel_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="images",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="images",
            field=models.CharField(default="", max_length=200),
        ),
    ]
