# Generated by Django 4.1.2 on 2024-02-15 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaleFemaleConnectionModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_blocked", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                ("is_request_sent", models.BooleanField(default=False)),
                ("is_request_accepted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_user",
                        to="user.usermodel",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_user",
                        to="user.usermodel",
                    ),
                ),
            ],
        ),
    ]
