# Generated by Django 4.1.2 on 2024-02-21 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("answerOfQuestions", "0002_alter_answersoffemalesmodel_is_deleted_and_more"),
        ("question", "0001_initial"),
        ("recordComparision", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultPointsSystemForAnswersModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("total_points", models.IntegerField(default=0)),
                ("is_match", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "female_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="answerOfQuestions.answersoffemalesmodel",
                    ),
                ),
                (
                    "female_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question.questionforfemalemodel",
                    ),
                ),
                (
                    "male_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="answerOfQuestions.answersofmalesmodel",
                    ),
                ),
                (
                    "male_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question.questionformalemodel",
                    ),
                ),
            ],
        ),
    ]
