# Generated by Django 4.1.2 on 2024-02-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordComparision", "0002_defaultpointssystemforanswersmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparingrecordsanswerwisemodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="defaultpointssystemforanswersmodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="totalrecordscomparisonmodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
