# Generated by Django 4.1.2 on 2024-02-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "questionOption",
            "0002_alter_questionoptionsforfemalesmodel_is_deleted_and_more",
        ),
        (
            "recordComparision",
            "0003_alter_comparingrecordsanswerwisemodel_is_deleted_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultpointssystemforanswersmodel",
            name="female_answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="questionOption.questionoptionsforfemalesmodel",
            ),
        ),
        migrations.AlterField(
            model_name="defaultpointssystemforanswersmodel",
            name="male_answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="questionOption.questionoptionsformalesmodel",
            ),
        ),
    ]
